# Generated by Django 4.2.9 on 2024-01-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("resource_id", models.CharField(blank=True, max_length=2048, null=True)),
                ("ca", models.CharField(blank=True, max_length=2048, null=True)),
                ("info", models.CharField(blank=True, max_length=2048, null=True)),
                ("date_published", models.CharField(blank=True, max_length=2048, null=True)),
                ("tenders_submission_deadline", models.CharField(blank=True, max_length=2048, null=True)),
                ("procedure", models.CharField(blank=True, max_length=2048, null=True)),
                ("status", models.CharField(blank=True, max_length=2048, null=True)),
                ("notice_pdf", models.CharField(blank=True, max_length=2048, null=True)),
                ("award_date", models.CharField(blank=True, max_length=2048, null=True)),
                ("estimated_value", models.CharField(blank=True, max_length=2048, null=True)),
                ("cycle", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenderDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tender_submission_deadline_in_days_hours", models.CharField(blank=True, max_length=2048, null=True)),
                ("name_of_contracting_authority", models.CharField(blank=True, max_length=2048, null=True)),
                ("publish_on_behalf_of", models.CharField(blank=True, max_length=2048, null=True)),
                ("participating_bodies", models.CharField(blank=True, max_length=2048, null=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("cft_ca_unique_id", models.CharField(blank=True, max_length=2048, null=True)),
                ("evaluation_mechanism", models.CharField(blank=True, max_length=2048, null=True)),
                ("description", models.CharField(blank=True, max_length=2048, null=True)),
                ("procurement_type", models.CharField(blank=True, max_length=2048, null=True)),
                ("directive", models.CharField(blank=True, max_length=2048, null=True)),
                ("procedure", models.CharField(blank=True, max_length=2048, null=True)),
                ("cft_involves", models.CharField(blank=True, max_length=2048, null=True)),
                ("cpv_codes", models.CharField(blank=True, max_length=2048, null=True)),
                ("contact_point", models.CharField(blank=True, max_length=2048, null=True)),
                ("award_per_item", models.CharField(blank=True, max_length=2048, null=True)),
                ("inclusion_of_e_auctions", models.CharField(blank=True, max_length=2048, null=True)),
                ("nuts_codes", models.CharField(blank=True, max_length=2048, null=True)),
                ("estimated_value_eur", models.CharField(blank=True, max_length=2048, null=True)),
                ("above_or_below_threshold", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "time_limit_for_receipt_of_tenders_or_requests_to_participate",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("deadline_for_dispatching_invitations", models.CharField(blank=True, max_length=2048, null=True)),
                ("end_of_clarification_period", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "upload_of_documents_within_the_clarifications",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("tenders_opening_date", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "allow_suppliers_to_make_an_online_expression_of_interest",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("contract_awarded_in_lots", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "contract_duration_in_months_or_years_excluding_extensions",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("validity_of_tender_in_days_or_months", models.CharField(blank=True, max_length=2048, null=True)),
                ("eu_funding", models.CharField(blank=True, max_length=2048, null=True)),
                ("multiple_tenders_will_be_accepted", models.CharField(blank=True, max_length=2048, null=True)),
                ("date_of_publication_invitation", models.CharField(blank=True, max_length=2048, null=True)),
                ("ted_links_for_published_notices", models.CharField(blank=True, max_length=2048, null=True)),
                ("date_of_awarding", models.CharField(blank=True, max_length=2048, null=True)),
                ("language_of_publication", models.CharField(blank=True, max_length=2048, null=True)),
                ("number_of_openers", models.CharField(blank=True, max_length=2048, null=True)),
                ("tender_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="scrape.tender")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
