# Generated by Django 4.2.9 on 2024-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenderdetail",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
