# Generated by Django 4.2.9 on 2024-01-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="other",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
