# Generated by Django 4.2.9 on 2024-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0002_alter_tender_info_alter_tenderdetail_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CftFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("addendum_id", models.CharField(blank=True, max_length=2048, null=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="cft_file/")),
                ("description", models.CharField(blank=True, max_length=2048, null=True)),
                ("lang", models.CharField(blank=True, max_length=2048, null=True)),
                ("doument_version", models.CharField(blank=True, max_length=2048, null=True)),
                ("action", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="tender",
            name="notice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="notice_pdf/"),
        ),
        migrations.AddField(
            model_name="tenderdetail",
            name="cft_file",
            field=models.ManyToManyField(to="scrape.cftfile"),
        ),
    ]
