# Generated by Django 4.2.9 on 2024-01-22 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0002_tender_other"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="other",
        ),
    ]
