# Generated by Django 4.2.9 on 2024-01-17 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0003_cftfile_alter_tender_notice_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="resource_id",
            field=models.CharField(
                default=datetime.datetime(2024, 1, 17, 17, 42, 39, 767194, tzinfo=datetime.timezone.utc),
                max_length=2048,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
