# Generated by Django 4.2.9 on 2024-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0004_alter_tender_resource_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="cft_file",
            field=models.ManyToManyField(to="scrape.cftfile"),
        ),
        migrations.AddField(
            model_name="tender",
            name="tender_detail",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name="TenderDetail",
        ),
    ]
