# Generated by Django 4.2.9 on 2024-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0005_tender_cft_file_tender_tender_detail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation_name", models.CharField(blank=True, max_length=2048, null=True)),
                ("ca_abbreviation", models.CharField(blank=True, max_length=2048, null=True)),
                ("ca_type", models.CharField(blank=True, max_length=2048, null=True)),
                ("annex", models.CharField(blank=True, max_length=2048, null=True)),
                ("address", models.CharField(blank=True, max_length=2048, null=True)),
                ("eircode_or_postal_code", models.CharField(blank=True, max_length=2048, null=True)),
                ("city", models.CharField(blank=True, max_length=2048, null=True)),
                ("county", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.CharField(blank=True, max_length=2048, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=2048, null=True)),
                ("fax", models.CharField(blank=True, max_length=2048, null=True)),
                ("website", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
