# Generated by Django 4.2.9 on 2024-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0006_clientinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="client_info",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="scrape.clientinfo"
            ),
        ),
    ]
