# Generated by Django 4.2.9 on 2024-01-18 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0008_alter_cftfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tender",
            old_name="cft_file",
            new_name="cft_files",
        ),
    ]
