# Generated by Django 4.2.9 on 2024-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0009_rename_cft_file_tender_cft_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="client_info",
        ),
        migrations.AddField(
            model_name="clientinfo",
            name="client_info_id",
            field=models.CharField(default=1, max_length=2048, unique=True),
            preserve_default=False,
        ),
    ]
