# Generated by Django 4.2.9 on 2024-01-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0011_rename_client_info_id_clientinfo_resource_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientinfo",
            name="resource_id",
        ),
        migrations.AddField(
            model_name="clientinfo",
            name="tendr_id",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="scrape.tender"
            ),
        ),
    ]
