# Generated by Django 4.2.9 on 2024-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0013_alter_cftfile_file_alter_tender_notice_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="cpv_code",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
