# Generated by Django 4.2.9 on 2024-01-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0014_tender_cpv_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="cpv_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
