# Generated by Django 4.2.9 on 2024-01-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0015_alter_tender_cpv_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
