# Generated by Django 4.2.9 on 2024-01-22 01:42

from django.db import migrations, models

def convert_char_to_int(apps, schema_editor):
    MyModel = apps.get_model('scrape', 'Tender')
    for obj in MyModel.objects.all():
        try:
            obj.estimated_value = int(obj.estimated_value)
        except ValueError:
            obj.estimated_value = None
        obj.save()

class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0016_alter_tender_date_published"),
    ]

    operations = [
        migrations.RunPython(convert_char_to_int),
        migrations.AlterField(
            model_name="tender",
            name="estimated_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
