# Generated by Django 4.2.9 on 2024-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0017_alter_tender_estimated_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="estimated_value",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
