# Generated by Django 4.2.9 on 2024-01-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0018_alter_tender_estimated_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="date_published",
            field=models.CharField(blank=True, null=True),
        ),
    ]
