# Generated by Django 4.2.9 on 2024-01-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0021_alter_tender_date_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="estimated_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
