# Generated by Django 4.2.9 on 2024-01-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0022_alter_tender_date_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="estimated_value",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
